GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBZmthciBNdWhhbWFkIiwiZW1haWwiOiJlbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE3MDI1Mzk2MTEsImV4cCI6MTcwMjUzOTYzMX0.T77qDpmgCZJkZH1Q0iNQ4f3xXZhr_inNuFGvNCt0Jr0

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Afkar Muhamad",
    "email": "email@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout